### GET /tasks
GET http://localhost:8080/tasks HTTP/1.1

### POST /tasks
POST http://localhost:8080/tasks HTTP/1.1
content-type: application/json

{
    "title": "Estudar Kubernetes",
    "description": "",
    "completed": false,
    "due_date": "2025-03-20T23:59:00Z"
}

### PUT /tasks
PUT http://localhost:8080/tasks/67ce224b57d75ca1fea5b466 HTTP/1.1
content-type: application/json

{
    "title": "Estudar Kubernetes 2",
    "description": "Estudar Kubernetes 2",
    "completed": true,
    "due_date": "2025-03-20T23:59:00Z"
}

### DELETE /tasks
DELETE http://localhost:8080/tasks/67cdff236099618fc51c21ea HTTP/1.1
