### GET /
GET http://localhost:8080 HTTP/1.1

### GET /tasks
GET http://localhost:8080/tasks HTTP/1.1

### POST /tasks
POST http://localhost:8080/tasks HTTP/1.1
content-type: application/json

{
    "title": "Estudar Kubernetes",
    "description": "",
    "completed": false,
    "due_date": "2025-03-20T23:59:00Z"
}

### PUT /tasks
PUT http://localhost:8080/tasks/67cde7cef869abfed672d420 HTTP/1.1
content-type: application/json

{
    "title": "Estudar GO 2",
    "description": "Melhorar o projeto com validações 2",
    "completed": true,
    "due_date": "2025-03-20T23:59:00Z",
    "created_at": "2025-03-09T18:57:02.537Z"
}

### DELETE /tasks
DELETE http://localhost:8080/tasks/67cdebea383535ba74879cd7 HTTP/1.1
